In [1]:
import numpy as np
import pandas as pd

## Question 1

In [2]:
np.__version__

'1.20.3'

## Question 2

In [3]:
pd.__version__

'1.3.3'

In [7]:
df = pd.read_csv('Data/dataset.csv')

In [9]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

## Question 3

In [23]:
df[ df.Make=='BMW' ].MSRP.mean()

61546.76347305389

## Question 4

In [28]:
df[ df.Year>=2015 ]['Engine HP'].isnull().sum()

51

## Question 5

In [37]:
mean_hp_before = df['Engine HP'].mean()
mean_hp_before

249.38607007176023

In [38]:
mean_hp_after = df['Engine HP'].fillna(Engine_HP_mean).mean()
mean_hp_after

249.38607007176

In [39]:
print(round(mean_hp_before))
print(round(mean_hp_after))

249
249


## Question 6

In [57]:
df_rr = df[ df.Make=='Rolls-Royce']
df_rr = df_rr[['Engine HP', 'Engine Cylinders', 'highway MPG']]
df_rr = df_rr.drop_duplicates()

In [58]:
X = df_rr.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [59]:
XTX = X.T.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [60]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [61]:
XTX_inv.sum()

0.032212320677486195

## Question 7

In [62]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [65]:
w = ( XTX_inv.dot(X.T) ).dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])